import {
  Faculty,
  Publication,
  Patent,
  Project,
  Student,
  Staff,
  PhdScholar,
  Announcement,
  Post,
  DepartmentKPIs,
} from "./types";

export const MOCK_FACULTY: (Faculty & {
  email: string;
  phone: string;
  image_url: string;
  experience_years: number;
  qualifications: Array<{ degree: string; institute: string; year: number }>;
  research_interests: string[];
})[] = [
  {
    id: "f1",
    user_id: "u1",
    full_name: "Dr. Rajesh Sharma",
    employee_code: "CS01",
    designation: "Professor & Head of Department",
    is_active: true,
    email: "rajesh@nith.ac.in",
    phone: "+91-1972-254101",
    image_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    experience_years: 18,
    research_interests: ["Cloud Computing", "Distributed Systems", "IoT Security"],
    qualifications: [
      { degree: "Ph.D. in Computer Science", institute: "IIT Roorkee", year: 2010 },
      { degree: "M.Tech CSE", institute: "NIT Hamirpur", year: 2005 },
      { degree: "B.Tech CSE", institute: "HP University", year: 2002 },
    ],
    profile: {
      faculty_id: "f1",
      specializations: "Cloud Computing, Distributed Algorithms, Network Security",
      google_scholar_id: "scholar_rajesh_sharma",
      scopus_id: "57193849100",
      orcid: "0000-0002-1825-0097",
      personal_website: "https://rajeshsharma.cse.nit.ac.in",
      bio: "Dr. Rajesh Sharma has over 18 years of teaching and research experience in high-performance cloud architectures. He has published 60+ IEEE/ACM journal and conference papers and authored 2 textbooks.",
      profile_image_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    },
  },
  {
    id: "f2",
    user_id: "u2",
    full_name: "Dr. Priya Verma",
    employee_code: "CS02",
    designation: "Associate Professor",
    is_active: true,
    email: "priya@nith.ac.in",
    phone: "+91-1972-254102",
    image_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
    experience_years: 12,
    research_interests: ["Artificial Intelligence", "Deep Learning", "Computer Vision"],
    qualifications: [
      { degree: "Ph.D. in Machine Learning", institute: "IIT Delhi", year: 2014 },
      { degree: "M.Tech CSE", institute: "IIT Kanpur", year: 2009 },
      { degree: "B.Tech IT", institute: "NIT Kurukshetra", year: 2007 },
    ],
    profile: {
      faculty_id: "f2",
      specializations: "Medical Image Analysis, Transformer Architectures, Explainable AI",
      google_scholar_id: "scholar_priya_verma",
      scopus_id: "57201948190",
      orcid: "0000-0003-4921-9912",
      personal_website: "https://priyaverma.ai",
      bio: "Dr. Priya Verma is an AI researcher focusing on deep learning applications for healthcare and biomedical imaging. Recipient of SERB Early Career Research Award.",
      profile_image_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
    },
  },
  {
    id: "f3",
    user_id: "u3",
    full_name: "Dr. Amit Kumar Gupta",
    employee_code: "CS03",
    designation: "Assistant Professor (Grade-I)",
    is_active: true,
    email: "amit.gupta@nith.ac.in",
    phone: "+91-1972-254103",
    image_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    experience_years: 8,
    research_interests: ["Cybersecurity", "Blockchain", "Cryptographic Protocols"],
    qualifications: [
      { degree: "Ph.D. in Information Security", institute: "IIT Kharagpur", year: 2018 },
      { degree: "M.Tech Information Security", institute: "NIT Allahabad", year: 2013 },
      { degree: "B.Tech CSE", institute: "NIT Hamirpur", year: 2011 },
    ],
    profile: {
      faculty_id: "f3",
      specializations: "Zero-Knowledge Proofs, Smart Contracts, Post-Quantum Cryptography",
      google_scholar_id: "scholar_amit_gupta",
      scopus_id: "57384910293",
      orcid: "0000-0001-9482-3841",
      personal_website: "https://amitgupta.security",
      bio: "Dr. Amit specializes in applied cryptography and decentralized systems. Principal Investigator for MeitY Cyber-Physical Systems grant.",
      profile_image_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    },
  },
  {
    id: "f4",
    user_id: "u4",
    full_name: "Dr. Sunita Kapoor",
    employee_code: "CS04",
    designation: "Assistant Professor",
    is_active: true,
    email: "sunita.k@nith.ac.in",
    phone: "+91-1972-254104",
    image_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80",
    experience_years: 6,
    research_interests: ["Natural Language Processing", "Large Language Models", "Information Retrieval"],
    qualifications: [
      { degree: "Ph.D. in Computer Science", institute: "IIIT Hyderabad", year: 2020 },
      { degree: "M.Tech CSE", institute: "IIIT Bangalore", year: 2015 },
      { degree: "B.Tech CSE", institute: "Thapar University", year: 2013 },
    ],
    profile: {
      faculty_id: "f4",
      specializations: "Indic Language Processing, Code-Mixed NLP, Sentiment Analysis",
      google_scholar_id: "scholar_sunita_kapoor",
      scopus_id: "57492019482",
      orcid: "0000-0002-8391-4920",
      personal_website: "https://sunitakapoor.nlp",
      bio: "Dr. Sunita works on low-resource Indian languages NLP and conversational AI. Has published extensively in ACL, EMNLP, and COLING.",
      profile_image_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80",
    },
  },
];

export const MOCK_PUBLICATIONS: Publication[] = [
  {
    id: "p1",
    title: "Adaptive Task Scheduling in Heterogeneous Fog-Cloud Computing Environments",
    publication_type: "JOURNAL",
    journal_or_conference_name: "IEEE Transactions on Cloud Computing",
    volume: "12",
    issue: "3",
    pages: "1420-1435",
    year: 2024,
    month: 5,
    doi: "10.1109/TCC.2024.3391024",
    issn_isbn: "2168-7161",
    impact_factor: 6.8,
    is_sci: true,
    is_scopus: true,
    is_peer_reviewed: true,
    abstract_text: "Fog computing extends cloud architecture to the edge of the network. This paper proposes an adaptive reinforcement learning-based task scheduling framework that minimizes deadline miss ratios while reducing carbon footprint.",
    publisher: "IEEE",
    authors: [
      { id: "a1", publication_id: "p1", faculty_id: "f1", author_name: "Dr. Rajesh Sharma", author_order: 1, is_corresponding: true },
      { id: "a2", publication_id: "p1", faculty_id: null, author_name: "Vikas Malhotra", author_order: 2, is_corresponding: false },
    ],
  },
  {
    id: "p2",
    title: "Multi-Modal Medical Image Segmentation using Hierarchical Vision Transformers",
    publication_type: "JOURNAL",
    journal_or_conference_name: "Medical Image Analysis (Elsevier)",
    volume: "94",
    issue: "1",
    pages: "103120",
    year: 2024,
    month: 8,
    doi: "10.1016/j.media.2024.103120",
    issn_isbn: "1361-8415",
    impact_factor: 10.9,
    is_sci: true,
    is_scopus: true,
    is_peer_reviewed: true,
    abstract_text: "Accurate organ and lesion segmentation in MRI/CT scans remains challenging due to boundary ambiguity. We present MedViT-Hier, a dual-path hierarchical vision transformer yielding 94.2% Dice score.",
    publisher: "Elsevier",
    authors: [
      { id: "a3", publication_id: "p2", faculty_id: "f2", author_name: "Dr. Priya Verma", author_order: 1, is_corresponding: true },
      { id: "a4", publication_id: "p2", faculty_id: null, author_name: "Aman Deep", author_order: 2, is_corresponding: false },
    ],
  },
  {
    id: "p3",
    title: "Zero-Knowledge Contingent Payments on Ethereum: Practical Protocols and Gas Optimization",
    publication_type: "CONFERENCE",
    journal_or_conference_name: "IEEE International Conference on Blockchain and Cryptocurrency (ICBC 2024)",
    volume: "",
    issue: "",
    pages: "210-218",
    year: 2024,
    month: 5,
    doi: "10.1109/ICBC60299.2024.10543201",
    issn_isbn: "979-8-3503-4921-2",
    impact_factor: 0,
    is_sci: false,
    is_scopus: true,
    is_peer_reviewed: true,
    abstract_text: "We demonstrate a privacy-preserving contingent payment protocol using Groth16 SNARKs with 40% reduced gas verification costs on EVM.",
    publisher: "IEEE",
    authors: [
      { id: "a5", publication_id: "p3", faculty_id: "f3", author_name: "Dr. Amit Kumar Gupta", author_order: 1, is_corresponding: true },
    ],
  },
  {
    id: "p4",
    title: "Low-Resource Cross-Lingual Transfer for Sentiment Analysis in Indic Code-Mixed Social Data",
    publication_type: "JOURNAL",
    journal_or_conference_name: "ACM Transactions on Asian and Low-Resource Language Information Processing",
    volume: "23",
    issue: "4",
    pages: "1-22",
    year: 2023,
    month: 11,
    doi: "10.1145/3610482",
    issn_isbn: "2375-4699",
    impact_factor: 2.3,
    is_sci: true,
    is_scopus: true,
    is_peer_reviewed: true,
    abstract_text: "Code-mixing between Hindi and English presents significant syntactic complexity. We introduce IndicBERT-Mix with phoneme-aware embeddings.",
    publisher: "ACM",
    authors: [
      { id: "a6", publication_id: "p4", faculty_id: "f4", author_name: "Dr. Sunita Kapoor", author_order: 1, is_corresponding: true },
    ],
  },
];

export const MOCK_PATENTS: Patent[] = [
  {
    id: "pat1",
    title: "An Energy-Efficient Fault-Tolerant Load Balancer for Distributed IoT Edge Clusters",
    application_number: "202311048921",
    patent_number: "IN 492019",
    status: "Granted",
    filing_date: "2022-04-15",
    grant_date: "2024-02-20",
    country: "India",
    patent_office: "Indian Patent Office (New Delhi)",
    abstract_text: "A system and apparatus for dynamic thermal-aware task scheduling among battery-operated edge compute units.",
  },
  {
    id: "pat2",
    title: "Deep Neural Network Based Automated Detection System for Diabetic Retinopathy from Low-Cost Fundus Cameras",
    application_number: "202311091240",
    patent_number: "",
    status: "Published",
    filing_date: "2023-09-10",
    grant_date: "",
    country: "India",
    patent_office: "Indian Patent Office (New Delhi)",
    abstract_text: "Real-time edge AI embedded hardware device for retinal anomaly screening in rural healthcare setups.",
  },
  {
    id: "pat3",
    title: "Cryptographic Hardware Accelerator for Post-Quantum Lattice-Based Key Encapsulation",
    application_number: "202411019283",
    patent_number: "",
    status: "Filed",
    filing_date: "2024-01-25",
    grant_date: "",
    country: "India",
    patent_office: "Indian Patent Office (New Delhi)",
    abstract_text: "FPGA-optimized Kyber-512 hardware implementation reducing modular multiplication cycles by 35%.",
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "prj1",
    title: "Design and Deployment of AI-Driven Secure Edge Computing Architecture for Smart Rural Infrastructure",
    funding_agency: "Ministry of Electronics and Information Technology (MeitY)",
    status: "Ongoing",
    project_type: "Sponsored R&D",
    start_date: "2023-04-01",
    end_date: "2026-03-31",
    total_sanctioned_amount: 8500000,
    total_amount_received: 4250000,
    scheme: "Cyber Physical Systems (CPS) Mission",
    reference_number: "MeitY/R&D/2023/CSE/084",
  },
  {
    id: "prj2",
    title: "Explainable Deep Learning for Automated Early Detection of Neurological Disorders from Brain MRIs",
    funding_agency: "Science and Engineering Research Board (SERB - DST)",
    status: "Ongoing",
    project_type: "Sponsored R&D",
    start_date: "2022-10-01",
    end_date: "2025-09-30",
    total_sanctioned_amount: 4850000,
    total_amount_received: 3600000,
    scheme: "Core Research Grant (CRG)",
    reference_number: "CRG/2022/003912",
  },
  {
    id: "prj3",
    title: "Zero-Trust Security Architecture for Industrial IoT in Critical Hydroelectric Infrastructure",
    funding_agency: "SJVN Limited (Hydroelectric Power)",
    status: "Completed",
    project_type: "Industry Sponsored",
    start_date: "2021-06-01",
    end_date: "2023-12-31",
    total_sanctioned_amount: 3200000,
    total_amount_received: 3200000,
    scheme: "Industry-Academia Collaborative Research",
    reference_number: "SJVN/TECH/2021/04",
  },
];

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann1",
    department_id: "22222222-2222-2222-2222-222222222222",
    title: "Call for Applications: Ph.D. Admissions (Autumn Session 2026-2027)",
    body: "Applications are invited from eligible candidates for full-time/part-time Ph.D. in Computer Science & Engineering. Written test & interviews scheduled for June 24-25, 2026.",
    publish_date: "2026-05-10",
    expiry_date: "2026-06-20",
    is_private: false,
  },
  {
    id: "ann2",
    department_id: "22222222-2222-2222-2222-222222222222",
    title: "Schedule for B.Tech CSE Final Year Major Project Demonstrations",
    body: "Final Year B.Tech students must submit their project reports and demonstrate working prototypes in Lab 3 from May 28 to May 30.",
    publish_date: "2026-05-02",
    expiry_date: "2026-06-05",
    is_private: false,
  },
  {
    id: "ann3",
    department_id: "22222222-2222-2222-2222-222222222222",
    title: "IEEE One-Week Faculty Development Programme on Generative AI & LLMs",
    body: "Join international experts from Academia and Industry from July 14-19, 2026. Hands-on coding with PyTorch and distributed training on NVIDIA H100 clusters.",
    publish_date: "2026-04-20",
    expiry_date: "2026-07-14",
    is_private: false,
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: "post1",
    department_id: "22222222-2222-2222-2222-222222222222",
    category: "Achievement",
    title: "CSE Student Team Wins 1st Prize at Smart India Hackathon 2025 (Hardware Edition)",
    slug: "sih-2025-first-prize-cse",
    body: "A 6-member team led by final year B.Tech students secured the 1st prize along with a cash award of ₹1,00,000 for their IoT-enabled Avalanche Warning System.",
    publish_date: "2025-12-18",
  },
  {
    id: "post2",
    department_id: "22222222-2222-2222-2222-222222222222",
    category: "ResearchNews",
    title: "Dr. Priya Verma receives SERB Technology Innovation Award for AI in Healthcare",
    slug: "dr-priya-serb-award",
    body: "Recognizing outstanding translational research in deep learning algorithms for radiological diagnosis in underprivileged healthcare centers.",
    publish_date: "2026-02-14",
  },
  {
    id: "post3",
    department_id: "22222222-2222-2222-2222-222222222222",
    category: "AcademicsNews",
    title: "Department launches new M.Tech Specialization in Artificial Intelligence & Data Science",
    slug: "mtech-ai-launch",
    body: "With a sanctioned intake of 30 students, the curriculum combines foundational machine learning, cloud engineering, and ethical AI.",
    publish_date: "2025-08-01",
  },
];

export const MOCK_STUDENTS: Student[] = [
  { id: "s1", department_id: "22222222-2222-2222-2222-222222222222", programme_id: "btech", name: "Aarav Sharma", roll_number: "22BCSE01", email: "22bcse01@nith.ac.in", batch_year: 2022, cgpa: 9.4 },
  { id: "s2", department_id: "22222222-2222-2222-2222-222222222222", programme_id: "btech", name: "Ananya Patel", roll_number: "22BCSE02", email: "22bcse02@nith.ac.in", batch_year: 2022, cgpa: 9.1 },
  { id: "s3", department_id: "22222222-2222-2222-2222-222222222222", programme_id: "btech", name: "Rohan Verma", roll_number: "22BCSE03", email: "22bcse03@nith.ac.in", batch_year: 2022, cgpa: 8.8 },
  { id: "s4", department_id: "22222222-2222-2222-2222-222222222222", programme_id: "mtech", name: "Divya Nambiar", roll_number: "24MCSE01", email: "24mcse01@nith.ac.in", batch_year: 2024, cgpa: 9.6 },
  { id: "s5", department_id: "22222222-2222-2222-2222-222222222222", programme_id: "mtech", name: "Kunal Mehra", roll_number: "24MCSE02", email: "24mcse02@nith.ac.in", batch_year: 2024, cgpa: 8.9 },
];

export const MOCK_STAFF: Staff[] = [
  { id: "st1", department_id: "22222222-2222-2222-2222-222222222222", name: "Sh. Ramesh Chand", designation: "Technical Officer (System Admin)", email: "ramesh@nith.ac.in", phone: "+91-1972-254120" },
  { id: "st2", department_id: "22222222-2222-2222-2222-222222222222", name: "Sh. Anil Kumar", designation: "Senior Lab Assistant (Networking & Cloud Lab)", email: "anil.lab@nith.ac.in", phone: "+91-1972-254121" },
  { id: "st3", department_id: "22222222-2222-2222-2222-222222222222", name: "Smt. Sunita Devi", designation: "Junior Assistant (Office Administration)", email: "office.cse@nith.ac.in", phone: "+91-1972-254122" },
];

export const MOCK_PHD_SCHOLARS: PhdScholar[] = [
  { id: "phd1", department_id: "22222222-2222-2222-2222-222222222222", name: "Vikas Malhotra", enrollment_number: "21PHDCSE01", topic: "Energy-Efficient Resource Allocation in Edge-Fog Architectures", supervisor_faculty_id: "f1", status: "pursuing", joining_date: "2021-08-10", completion_date: "" },
  { id: "phd2", department_id: "22222222-2222-2222-2222-222222222222", name: "Aman Deep", enrollment_number: "22PHDCSE03", topic: "Deep Learning based Automated Volumetric Brain Tumor Segmentation", supervisor_faculty_id: "f2", status: "pursuing", joining_date: "2022-01-15", completion_date: "" },
  { id: "phd3", department_id: "22222222-2222-2222-2222-222222222222", name: "Dr. Rohit Sen", enrollment_number: "19PHDCSE02", topic: "Scalable Consensus Algorithms for Private Blockchain Networks", supervisor_faculty_id: "f3", status: "passed", joining_date: "2019-07-20", completion_date: "2024-04-12" },
];

export const MOCK_DEPARTMENT_KPIS: DepartmentKPIs = {
  department_id: "22222222-2222-2222-2222-222222222222",
  department_name: "Computer Science & Engineering",
  faculty_count: 24,
  staff_count: 8,
  total_students: 580,
  total_publications: 342,
  patent_count: 28,
  ongoing_projects: 14,
  total_sanctioned_amount: 38500000,
  event_count: 45,
};

export const MOCK_PLACEMENT_STATS = [
  { year: 2025, branch: "B.Tech CSE", graduating: 120, placed: 116, offers: 154, highest_lpa: 54.0, avg_lpa: 18.2, median_lpa: 15.0 },
  { year: 2025, branch: "M.Tech CSE", graduating: 28, placed: 26, offers: 32, highest_lpa: 32.0, avg_lpa: 14.5, median_lpa: 12.0 },
  { year: 2024, branch: "B.Tech CSE", graduating: 115, placed: 111, offers: 148, highest_lpa: 52.5, avg_lpa: 17.8, median_lpa: 14.2 },
  { year: 2024, branch: "M.Tech CSE", graduating: 25, placed: 24, offers: 28, highest_lpa: 28.0, avg_lpa: 13.8, median_lpa: 11.5 },
  { year: 2023, branch: "B.Tech CSE", graduating: 110, placed: 108, offers: 142, highest_lpa: 48.0, avg_lpa: 16.9, median_lpa: 13.5 },
];

export const MOCK_COURSES = [
  { code: "CS-201", name: "Data Structures & Algorithms", credits: 4, semester: 3, level: "UG", type: "Core" },
  { code: "CS-202", name: "Discrete Mathematics", credits: 4, semester: 3, level: "UG", type: "Core" },
  { code: "CS-203", name: "Digital Logic Design", credits: 4, semester: 3, level: "UG", type: "Core" },
  { code: "CS-301", name: "Database Management Systems", credits: 4, semester: 5, level: "UG", type: "Core" },
  { code: "CS-302", name: "Operating Systems", credits: 4, semester: 5, level: "UG", type: "Core" },
  { code: "CS-303", name: "Computer Networks", credits: 4, semester: 5, level: "UG", type: "Core" },
  { code: "CS-401", name: "Artificial Intelligence & Machine Learning", credits: 4, semester: 7, level: "UG", type: "Core" },
  { code: "CS-421", name: "Cloud Computing & Distributed Systems", credits: 3, semester: 7, level: "UG", type: "Elective" },
  { code: "CS-422", name: "Blockchain & Cryptographic Engineering", credits: 3, semester: 7, level: "UG", type: "Elective" },
  { code: "CS-601", name: "Advanced Algorithms & Complexity", credits: 4, semester: 1, level: "PG", type: "Core" },
  { code: "CS-602", name: "Deep Learning Architectures", credits: 4, semester: 1, level: "PG", type: "Core" },
];

export const MOCK_LABS = [
  { id: "lab1", name: "High-Performance Cloud & Distributed Systems Lab", location: "Block C, Room 204", head: "Dr. Rajesh Sharma", equipment_count: 45, description: "Equipped with 4-node Supermicro GPU cluster, high-speed 10Gbps Infiniband switch, and virtualized OpenStack testbed for distributed computing experiments." },
  { id: "lab2", name: "Artificial Intelligence & Medical Vision Lab", location: "Block C, Room 301", head: "Dr. Priya Verma", equipment_count: 32, description: "Houses NVIDIA RTX A6000 and Tesla V100 workstations dedicated to biomedical image segmentation and deep transformer training." },
  { id: "lab3", name: "Cybersecurity & Blockchain Research Lab", location: "Block C, Room 305", head: "Dr. Amit Kumar Gupta", equipment_count: 28, description: "Equipped with isolated network simulation racks, hardware security modules (HSM), and FPGA development boards for post-quantum crypto acceleration." },
  { id: "lab4", name: "General Computing & UG Programming Lab", location: "Block C, Room 101", head: "Sh. Ramesh Chand", equipment_count: 75, description: "75 Intel Core i7 workstations running dual-boot Linux/Windows for undergraduate lab instruction in DSA, OOP, and Web Systems." },
];
